id: PA5C99C3C
initial_creation_type: ocr
source_metadata:
  volumes:
    96c862c05d0d4c10895b674105989417:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
